### ISSUE TITLE
NCONTAINS constraint type is not working properly

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#241]
![Screenshot 2024-05-28 at 2 40 50 PM](https://github.com/MathematicalMedicine/diver-issues/assets/3909236/b5e32181-5107-4452-b786-1bc9531b8f61)

**Comment by Viqsi** [comment]
We've determined it's because the regex provided is bad - RLIKE '[^4]' means has at least one value that is not 4.

A proper fix would be use of NOT RLIKE, but that would take Bonus Effort(tm) because of how constraint types are defined in diverweb (presence of any regex implies use of RLIKE; NOT RLIKE would need something different - oh, and that'd be a new Preview/NewCohort proc pair).

**Comment by Viqsi** [comment]
Turns out that the constraints handling in diverweb is actually fairly isolated because we just don't use it in all that many places. So this is less effort than I'd anticipated. Giving it a shot now.

**Comment by Viqsi** [comment]
This was being done for a CUSTOM VARIABLE, not a cohort. That is not fixed.
