### ISSUE TITLE
Must "SQL-sanitize" construct variable names, values and descriptions for both

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#85]
Since we are using SQL itself to compute values in new tables from construct variables and their values, we need to ensure that his parents cannot name a construct variable after "Jonny '; Drop table users;"

**Comment by Viqsi** [comment]
[Little Bobby Tables](https://xkcd.com/327/), we call him. 😉

Defending against this is one of those things that we normally get "for free" as a result of using prepared statements in Python (in diverRPC) to pass parameters to SPs; it's part of why just relaying JSON documents is troublesome. But *that*'s an even more massive can of worms.

**Comment by Viqsi** [comment]
The commit referencing this only partially addresses the issue. From diverweb, the user can only input a variable name that is alphanumerics or underscore (exclude `[^a-zA-Z0-9_]`).

The API directly, and all other fields, are still vulnerable.

**Comment by Viqsi** [comment]
Some of the injection concerns *may* already be covered by some of the parameterization we already do; it's just a question of how much work pymysql already does with JSON documents (normally it only likes strings). It's something I really need to test more.

#184 would be a big part of helping that along and so it's on my list of Things To Do. Those two things alone would help a great deal. I also fully intend to pare down what actually gets parsed in SQL to just the construct value definitions.

Ultimately, though I suspect the solution is going to involve parsing the whole document in diverAPI/diverRPC somehow. I'm kind of searching and reading frantically to try to avoid having to do that, though. (Mostly because *if* we do that, it'd likely lead to the further deprecation of Combine Multiple.)

**Comment by Viqsi** [comment]
I may now have some strategery for handling this more sanely. It's going to involve reducing all our current parsing to just the "constraints" section of the value definitions so as to reduce the attack surface - because after that, extracted values are guaranteed to be one of the following that we can check before using in dynamic SQL:
1. One of the contributing variables in the list of variables provided with the initial request
2. One of the comparison-type shortcodes - EQ, NEQ, GT, LT, et cetera
3. A valid value for the associated contributing variable (identified in item 1 above)

Number 3 would be the biggest sticking point because that might require a few JOINs to bring in the appropriate variable's regex for validating purposes. But it *is* hypothetically possible to do that entirely within a SQL procedure, *without* using dynamic SQL (or anything else that requires direct string interpolation and thus risks an injection attack).
