### ISSUE TITLE
Replace "Download specified number of rows" with a Preview Download capability

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#98]
Download was defined for an 18K row cohort using a variable set with 2 variables (1 being a construct).  I select download 20 rows, but got all of them:
![Screen Shot 2023-02-16 at 11 08 19 AM](https://user-images.githubusercontent.com/3909236/219423209-be68d54f-56d1-4459-b34c-803221f210af.png)
![Screen Shot 2023-02-16 at 11 08 52 AM](https://user-images.githubusercontent.com/3909236/219423230-9fdd157f-e009-4ae3-87f3-0d50269cf78d.png)

**Comment by Viqsi** [comment]
I think there's a design question as to whether or not we actually *do* want to have that "specified number" in the first place. At the moment the value isn't even submitted in any form to the API endpoint; it's just blithely ignored. (And the endpoint doesn't even *have* a "restrict to number of rows" parameter...).

So this is less a bug and more a Not Yet Implemented. And I'm not sure if we even want to do so...

**Comment by Viqsi** [comment]
Sort of like a "Preview Download" operation?

I guess part of my flinching at that is that due to the way downloads are presently constructed, there is literally no difference between a "preview" and a complete download (the whole thing is constructed regardless). I would therefore at a minimum want "preview" operations to be tracked in such a fashion that we know this is not an Actual Complete Data Download and it can be disposed of willy-nilly at any time.

But that requires adding sophistication to the backend. Or, IOW, work for you... 😁

**Comment by Viqsi** [comment]
This has shown up in Veronica's todo document:
> •	Download should have preview option : not an option to download first x rows, but an option to preview (view) first y col's for first x rows (can fix max number of col'ns)

My concerns about backend processing time (none is saved) still remain, but the use case for this seems to be about the amount of time the user has to be downloading a large file, rather than worrying about our resource consumption. So, okay. It's doable, and I'll work on doing it.
